name: PR Check

on:
  pull_request:
    branches:
      - 'main'

jobs:
  check:
    name: Build
    strategy:
      matrix:
        jdk: [21, 25]
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.jdk }}
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic
          cache-read-only: true

      - name: Run tests
        run: ./gradlew --no-daemon --no-parallel --continue check

      - name: Test Reports
        uses: codecov/codecov-action@v7
        if: success() || failure()
        with:
          report_type: test_results
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Test coverage reports
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
